pool: ADO_Github_Infra

trigger: none

jobs:
- job: TerraformInitplan
  displayName: Terraform Init Plan
  steps:
  - task: TerraformTask@5
    inputs:
      provider: 'azurerm'
      command: 'init'
      workingDirectory: '$(System.DefaultWorkingDirectory)/Environment/Test'
      commandOptions: '-upgrade'
      backendServiceArm: 'ADO_Infra'
      backendAzureRmResourceGroupName: 'RG_Practice1'
      backendAzureRmStorageAccountName: 'shubhamsinghvi403424'
      backendAzureRmContainerName: 'adocontainer'
      backendAzureRmKey: 'terraform.tfstate'

  - task: TerraformTask@5
    inputs:
      provider: 'azurerm'
      command: 'plan'
      workingDirectory: '$(System.DefaultWorkingDirectory)/Environment/Test'
      environmentServiceNameAzureRM: 'ADO_Infra'

- job: ManualValidation
  dependsOn: TerraformInitplan
  displayName: Validation Befor apply
  pool: server
  steps: 
  - task: ManualValidation@1
    inputs:
      notifyUsers: 'shubhamsinghvi8696@gmail.com'
      instructions: 'PLease validate Terraform plan'

- job: TwrraformApply
  dependsOn: ManualValidation
  displayName: Terraform apply
  steps:       
  - task: TerraformTask@5
    displayName: Terraform Init
    inputs:

      provider: 'azurerm'
      command: 'init'
      workingDirectory: '$(System.DefaultWorkingDirectory)/Environment/Test'
      commandOptions: '-upgrade'
      backendServiceArm: 'ADO_Infra'
      backendAzureRmResourceGroupName: 'RG_Practice1'
      backendAzureRmStorageAccountName: 'shubhamsinghvi403424'
      backendAzureRmContainerName: 'adocontainer'
      backendAzureRmKey: 'terraform.tfstate'

  - task: TerraformTask@5    
    displayName: Terraform apply  
    inputs:
      provider: 'azurerm'
      command: 'apply'
      ommandOptions: '-auto-approve'
      environmentServiceNameAzureRM: 'ADO_Infra'




  