pool: ADO_Github_Infra

trigger: none

stages: 
- stage: TerraformInitplan
  displayName: Terraform Init and Plan
  jobs:
  - job: TerraformInitplan
    displayName: Terraform Init Plan
    steps:
    
    # - task: tfsec@1
    #   inputs:
    #     version: 'v1.26.0'
    #     dir: 'System.DefaultWorkingDirectory)/Environment/Test'
    
    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)/Environment/Test'
        backendServiceArm: 'Azure_Github_Resources'
        backendAzureRmResourceGroupName: 'RG_Practice1'
        backendAzureRmStorageAccountName: 'shubhamsinghvi40342411'
        backendAzureRmContainerName: 'adocontainer'
        backendAzureRmKey: 'terraform.tfstate'

    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'plan'
        workingDirectory: '$(System.DefaultWorkingDirectory)/Environment/Test'
        environmentServiceNameAzureRM: 'Azure_Github_Resources'
    
- stage: TerraformInitapply
  dependsOn: TerraformInitplan
  displayName: Terraform Init and Apply
  jobs:
  - job: ManualValidation
    displayName: Validation Befor apply
    pool: server
    steps: 
    - task: ManualValidation@1
      inputs:
        notifyUsers: 'shubhamsinghvi8696@gmail.com'
        instructions: 'PLease validate Terraform plan'

  - job: TwrraformApply
    dependsOn: ManualValidation
    displayName: Terraform apply
    steps:       
    - task: TerraformTask@5
      displayName: Terraform Init
      inputs:

        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)/Environment/Test'
        commandOptions: '-upgrade'
        backendServiceArm: 'Azure_Github_Resources'
        backendAzureRmResourceGroupName: 'RG_Practice1'
        backendAzureRmStorageAccountName: 'shubhamsinghvi40342411'
        backendAzureRmContainerName: 'adocontainer'
        backendAzureRmKey: 'terraform.tfstate'

    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'apply'
        workingDirectory: '$(System.DefaultWorkingDirectory)/Environment/Test'
        environmentServiceNameAzureRM: 'Azure_Github_Resources'
