pool: ADO_Github_Infra

trigger: none

steps: 

- task: TerraformTask@5
  displayName: Terraform Init
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/Environment/Test'
    backendServiceArm: 'ADO_Infra'
    backendAzureRmResourceGroupName: 'RG_Practice1'
    backendAzureRmStorageAccountName: 'shubhamsinghvi403424'
    backendAzureRmContainerName: 'adocontainer'
    backendAzureRmKey: 'terraform.tfstate'

- task: TerraformTask@5
  displayName: Terraform plan
  inputs:
    provider: 'azurerm'
    command: 'plan'
    workingDirectory: '$(System.DefaultWorkingDirectory)/Environment/Test'
    environmentServiceNameAzureRM: 'ADO_Infra'